
var __cov_Yzq$qGr9jAv_2HhdEEX4TA = (Function('return this'))();
if (!__cov_Yzq$qGr9jAv_2HhdEEX4TA.__coverage__) { __cov_Yzq$qGr9jAv_2HhdEEX4TA.__coverage__ = {}; }
__cov_Yzq$qGr9jAv_2HhdEEX4TA = __cov_Yzq$qGr9jAv_2HhdEEX4TA.__coverage__;
if (!(__cov_Yzq$qGr9jAv_2HhdEEX4TA['/home/ubuntudev/Documents/NetBeans Projects/ConsunetApps/WhisperNote/src/constants.js'])) {
   __cov_Yzq$qGr9jAv_2HhdEEX4TA['/home/ubuntudev/Documents/NetBeans Projects/ConsunetApps/WhisperNote/src/constants.js'] = {"path":"/home/ubuntudev/Documents/NetBeans Projects/ConsunetApps/WhisperNote/src/constants.js","s":{"1":0,"2":0,"3":0,"4":0},"b":{},"f":{},"fnMap":{},"statementMap":{"1":{"start":{"line":13,"column":0},"end":{"line":13,"column":30}},"2":{"start":{"line":15,"column":0},"end":{"line":15,"column":105}},"3":{"start":{"line":16,"column":0},"end":{"line":16,"column":97}},"4":{"start":{"line":17,"column":0},"end":{"line":17,"column":26}}},"branchMap":{},"code":["(function () { /**"," * @file externalised constants relating to WhisperNote"," */ ","","/**"," * @namespace CONST"," * @type {object}"," * @description"," * <p>"," * Externalised constants relating to WhisperNote"," * </p>"," */","CONST.appName = 'WhisperNote';","    ","CONST.variableCypherSettings.cattname = { desc: \"Attachment filename\", type: \"string\", mandatory: false};","CONST.variableCypherSettings.catt = { desc: \"Attachment data\", type: \"object\", mandatory: false};","CONST.attSliceSize = 1024;","}());"]};
}
__cov_Yzq$qGr9jAv_2HhdEEX4TA = __cov_Yzq$qGr9jAv_2HhdEEX4TA['/home/ubuntudev/Documents/NetBeans Projects/ConsunetApps/WhisperNote/src/constants.js'];
__cov_Yzq$qGr9jAv_2HhdEEX4TA.s['1']++;CONST.appName='WhisperNote';__cov_Yzq$qGr9jAv_2HhdEEX4TA.s['2']++;CONST.variableCypherSettings.cattname={desc:'Attachment filename',type:'string',mandatory:false};__cov_Yzq$qGr9jAv_2HhdEEX4TA.s['3']++;CONST.variableCypherSettings.catt={desc:'Attachment data',type:'object',mandatory:false};__cov_Yzq$qGr9jAv_2HhdEEX4TA.s['4']++;CONST.attSliceSize=1024;
