
var __cov_AuIHHiayNmUMNWxppgakpA = (Function('return this'))();
if (!__cov_AuIHHiayNmUMNWxppgakpA.__coverage__) { __cov_AuIHHiayNmUMNWxppgakpA.__coverage__ = {}; }
__cov_AuIHHiayNmUMNWxppgakpA = __cov_AuIHHiayNmUMNWxppgakpA.__coverage__;
if (!(__cov_AuIHHiayNmUMNWxppgakpA['/home/ubuntudev/Documents/NetBeans Projects/ConsunetApps/common/src/constants.js'])) {
   __cov_AuIHHiayNmUMNWxppgakpA['/home/ubuntudev/Documents/NetBeans Projects/ConsunetApps/common/src/constants.js'] = {"path":"/home/ubuntudev/Documents/NetBeans Projects/ConsunetApps/common/src/constants.js","s":{"1":0},"b":{},"f":{},"fnMap":{},"statementMap":{"1":{"start":{"line":13,"column":0},"end":{"line":34,"column":2}}},"branchMap":{},"code":["(function () { /**"," * @file externalised constants relating to SCA Apps"," */ ","","/**"," * @namespace SCA_CONSTANTS"," * @type {object}"," * @description"," * <p>"," * Externalised constants relating to SCA Apps"," * </p>"," */","var CONST = {","    version: 1.4,","    cypherSettings: {","        iter: 1000, // maintained for backwards compatibility","        ks: 256, // maintained for backwards compatibility","        ts: 128, // maintained for backwards compatibility","        mode: \"ocb2\", // maintained for backwards compatibility","        cipher: \"aes\", // maintained for backwards compatibility","        keyHashAlgorithm: \"SHA-256\",","        cipherAlgorithm: \"AES-CBC\"","    },","    variableCypherSettings: {","        v:  { desc: \"<%= Version %>\", type: \"number\", mandatory: true},","        iv: { desc: \"<%= InitialisationVector %>\", type: \"string\", mandatory: true},","        salt: { desc: \"<%= Salt %>\", type: \"string\", mandatory: false}, // maintained for backwards compatibility","        adata: { desc: \"<%= Hint %>\", type: \"string\", mandatory: false},","        ct: { desc: \"<%= CypherText %>\", type: \"string\", mandatory: false}","    },","    regexEncryptedData: /<script id=\"encrypted-data\" type=\"text\\/javascript\">var encData=(.+);<\\/script>/g,","    regexAppType: /<meta name=\"sca-app-type\" content=\"(\\w+)\"/g,","    defaultTimeoutPeriodMins: 2","};","}());"]};
}
__cov_AuIHHiayNmUMNWxppgakpA = __cov_AuIHHiayNmUMNWxppgakpA['/home/ubuntudev/Documents/NetBeans Projects/ConsunetApps/common/src/constants.js'];
__cov_AuIHHiayNmUMNWxppgakpA.s['1']++;var CONST={version:1.4,cypherSettings:{iter:1000,ks:256,ts:128,mode:'ocb2',cipher:'aes',keyHashAlgorithm:'SHA-256',cipherAlgorithm:'AES-CBC'},variableCypherSettings:{v:{desc:'<%= Version %>',type:'number',mandatory:true},iv:{desc:'<%= InitialisationVector %>',type:'string',mandatory:true},salt:{desc:'<%= Salt %>',type:'string',mandatory:false},adata:{desc:'<%= Hint %>',type:'string',mandatory:false},ct:{desc:'<%= CypherText %>',type:'string',mandatory:false}},regexEncryptedData:/<script id="encrypted-data" type="text\/javascript">var encData=(.+);<\/script>/g,regexAppType:/<meta name="sca-app-type" content="(\w+)"/g,defaultTimeoutPeriodMins:2};
